<?php

namespace Database\Seeders;

use App\Models\Community;
use Illuminate\Database\Seeder;

class CommunitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $communities = [
            // Tacloban City Barangays
            ['name' => 'Diit', 'municipality' => 'Tacloban City', 'province' => 'Leyte', 'description' => 'Coastal barangay with diverse economic activities and fishing communities.', 'contact_person' => 'Brgy. Captain Juan Santos', 'contact_number' => '+63 (905) 123-4567', 'email' => 'diit@tacloban.gov.ph', 'address' => 'Diit, Tacloban City, Leyte', 'status' => 'active', 'notes' => 'Fishing and agriculture-based community'],
            ['name' => 'San Jose', 'municipality' => 'Tacloban City', 'province' => 'Leyte', 'description' => 'Urban barangay with commercial activities and strong community organizations.', 'contact_person' => 'Brgy. Captain Maria Cruz', 'contact_number' => '+63 (905) 234-5678', 'email' => 'sanjose@tacloban.gov.ph', 'address' => 'San Jose, Tacloban City, Leyte', 'status' => 'active', 'notes' => 'Urban community with livelihood programs'],
            ['name' => 'North Pabahay', 'municipality' => 'Tacloban City', 'province' => 'Leyte', 'description' => 'Residential community with strong community organization and livelihood initiatives.', 'contact_person' => 'Brgy. Captain Pedro Reyes', 'contact_number' => '+63 (905) 345-6789', 'email' => 'northpabahay@tacloban.gov.ph', 'address' => 'North Pabahay, Tacloban City, Leyte', 'status' => 'active', 'notes' => 'Residential area with active cooperative'],
            ['name' => 'Marasbaras', 'municipality' => 'Tacloban City', 'province' => 'Leyte', 'description' => 'Agricultural and fishing community with rich cultural heritage and traditions.', 'contact_person' => 'Brgy. Captain Rosa Villarosa', 'contact_number' => '+63 (905) 456-7890', 'email' => 'marasbaras@tacloban.gov.ph', 'address' => 'Marasbaras, Tacloban City, Leyte', 'status' => 'active', 'notes' => 'Farming and fishing-based economy'],
            ['name' => 'Magallanes', 'municipality' => 'Tacloban City', 'province' => 'Leyte', 'description' => 'Vibrant community with active health and livelihood extension programs.', 'contact_person' => 'Brgy. Captain Antonio Fernandez', 'contact_number' => '+63 (905) 567-8901', 'email' => 'magallanes@tacloban.gov.ph', 'address' => 'Magallanes, Tacloban City, Leyte', 'status' => 'active', 'notes' => 'Active in health and livelihood programs'],
            ['name' => 'South Pabahay', 'municipality' => 'Tacloban City', 'province' => 'Leyte', 'description' => 'Residential barangay with growing youth programs and educational initiatives.', 'contact_person' => 'Brgy. Captain Carlos Mendoza', 'contact_number' => '+63 (905) 678-9012', 'email' => 'southpabahay@tacloban.gov.ph', 'address' => 'South Pabahay, Tacloban City, Leyte', 'status' => 'active', 'notes' => 'Youth and education-focused programs'],
            ['name' => 'Dolores', 'municipality' => 'Tacloban City', 'province' => 'Leyte', 'description' => 'Agricultural community focusing on rice and vegetable farming.', 'contact_person' => 'Brgy. Captain Elena Santos', 'contact_number' => '+63 (905) 789-0123', 'email' => 'dolores@tacloban.gov.ph', 'address' => 'Dolores, Tacloban City, Leyte', 'status' => 'active', 'notes' => 'Agricultural hub with rice paddies'],
            ['name' => 'Tigbao', 'municipality' => 'Tacloban City', 'province' => 'Leyte', 'description' => 'Rural barangay with traditional farming and indigenous livelihood practices.', 'contact_person' => 'Brgy. Captain Fernando Lopez', 'contact_number' => '+63 (905) 890-1234', 'email' => 'tigbao@tacloban.gov.ph', 'address' => 'Tigbao, Tacloban City, Leyte', 'status' => 'active', 'notes' => 'Traditional farming practices'],
            ['name' => 'Mantawi', 'municipality' => 'Tacloban City', 'province' => 'Leyte', 'description' => 'Fishing community with small-scale aquaculture and maritime activities.', 'contact_person' => 'Brgy. Captain Roberto Dela Cruz', 'contact_number' => '+63 (905) 901-2345', 'email' => 'mantawi@tacloban.gov.ph', 'address' => 'Mantawi, Tacloban City, Leyte', 'status' => 'active', 'notes' => 'Fishing and aquaculture community'],
            ['name' => 'Felicidad', 'municipality' => 'Tacloban City', 'province' => 'Leyte', 'description' => 'Mixed livelihood community with small businesses and agriculture.', 'contact_person' => 'Brgy. Captain Ana Reyes', 'contact_number' => '+63 (905) 012-3456', 'email' => 'felicidad@tacloban.gov.ph', 'address' => 'Felicidad, Tacloban City, Leyte', 'status' => 'active', 'notes' => 'Mixed income sources'],
            
            // Nearby Municipalities in Leyte
            ['name' => 'Palo', 'municipality' => 'Palo', 'province' => 'Leyte', 'description' => 'Historic town known for agriculture and heritage sites.', 'contact_person' => 'Mayor Vicente Gonzalez', 'contact_number' => '+63 (905) 123-4567', 'email' => 'municipal@palo.gov.ph', 'address' => 'Palo, Leyte', 'status' => 'active', 'notes' => 'Historic and agricultural municipality'],
            ['name' => 'Tanauan', 'municipality' => 'Tanauan', 'province' => 'Leyte', 'description' => 'Fishing town with strong maritime economy.', 'contact_person' => 'Mayor Manuel Tabangcot', 'contact_number' => '+63 (905) 234-5678', 'email' => 'municipal@tanauan.gov.ph', 'address' => 'Tanauan, Leyte', 'status' => 'active', 'notes' => 'Maritime and fishing-based economy'],
            ['name' => 'Santa Fe', 'municipality' => 'Santa Fe', 'province' => 'Leyte', 'description' => 'Agricultural municipality with coconut and fruit farming.', 'contact_person' => 'Mayor Ana Maria Santos', 'contact_number' => '+63 (905) 345-6789', 'email' => 'municipal@santafe.gov.ph', 'address' => 'Santa Fe, Leyte', 'status' => 'active', 'notes' => 'Coconut and fruit farming hub'],
            ['name' => 'Matalom', 'municipality' => 'Matalom', 'province' => 'Leyte', 'description' => 'Rural municipality with farming and fishing combined livelihoods.', 'contact_person' => 'Mayor Ramon Flores', 'contact_number' => '+63 (905) 456-7890', 'email' => 'municipal@matalom.gov.ph', 'address' => 'Matalom, Leyte', 'status' => 'active', 'notes' => 'Mixed agriculture-fishing economy'],
            ['name' => 'Santo Niño', 'municipality' => 'Santo Niño', 'province' => 'Leyte', 'description' => 'Small municipality with agricultural focus and community development.', 'contact_person' => 'Mayor Lucia Mercado', 'contact_number' => '+63 (905) 567-8901', 'email' => 'municipal@santonino.gov.ph', 'address' => 'Santo Niño, Leyte', 'status' => 'active', 'notes' => 'Agriculture-focused development'],
            
            // Samar Province - Northern Samar
            ['name' => 'Calbayog City', 'municipality' => 'Calbayog City', 'province' => 'Samar', 'description' => 'City with vibrant commerce, fishing, and agricultural sectors.', 'contact_person' => 'Mayor Rolando Aquino', 'contact_number' => '+63 (905) 678-9012', 'email' => 'municipal@calbayog.gov.ph', 'address' => 'Calbayog City, Samar', 'status' => 'active', 'notes' => 'Urban coastal city with commerce'],
            ['name' => 'Catbalogan City', 'municipality' => 'Catbalogan City', 'province' => 'Samar', 'description' => 'Regional hub with diverse economic and educational institutions.', 'contact_person' => 'Mayor Gregorio Sanchez', 'contact_number' => '+63 (905) 789-0123', 'email' => 'municipal@catbalogan.gov.ph', 'address' => 'Catbalogan City, Samar', 'status' => 'active', 'notes' => 'Regional hub and city center'],
            ['name' => 'Paranas', 'municipality' => 'Paranas', 'province' => 'Samar', 'description' => 'Coastal municipality with fishing and small-scale commerce.', 'contact_person' => 'Mayor Patricia Reyes', 'contact_number' => '+63 (905) 890-1234', 'email' => 'municipal@paranas.gov.ph', 'address' => 'Paranas, Samar', 'status' => 'active', 'notes' => 'Coastal fishing community'],
            ['name' => 'San Jorge', 'municipality' => 'San Jorge', 'province' => 'Samar', 'description' => 'Municipality with fishing industry and community-based tourism.', 'contact_person' => 'Mayor Eduardo Marcos', 'contact_number' => '+63 (905) 901-2345', 'email' => 'municipal@sanjorge.gov.ph', 'address' => 'San Jorge, Samar', 'status' => 'active', 'notes' => 'Fishing and tourism-based'],
            ['name' => 'San Sebastian', 'municipality' => 'San Sebastian', 'province' => 'Samar', 'description' => 'Rural municipality with strong agricultural sector.', 'contact_person' => 'Mayor Marcelina Fernandez', 'contact_number' => '+63 (905) 012-3456', 'email' => 'municipal@sansebastian.gov.ph', 'address' => 'San Sebastian, Samar', 'status' => 'active', 'notes' => 'Rural agriculture community'],
            ['name' => 'Villareal', 'municipality' => 'Villareal', 'province' => 'Samar', 'description' => 'Agricultural municipality with rice farming and livestock raising.', 'contact_person' => 'Mayor Artemio Solis', 'contact_number' => '+63 (905) 123-4567', 'email' => 'municipal@villareal.gov.ph', 'address' => 'Villareal, Samar', 'status' => 'active', 'notes' => 'Agriculture and livestock hub'],
            ['name' => 'Pagsanghan', 'municipality' => 'Pagsanghan', 'province' => 'Samar', 'description' => 'Coastal municipality with fishing as primary livelihood.', 'contact_person' => 'Mayor Ernesto Lim', 'contact_number' => '+63 (905) 234-5678', 'email' => 'municipal@pagsanghan.gov.ph', 'address' => 'Pagsanghan, Samar', 'status' => 'active', 'notes' => 'Primary fishing livelihood'],
            ['name' => 'Jiabong', 'municipality' => 'Jiabong', 'province' => 'Samar', 'description' => 'Rural municipality with farming and small-scale industries.', 'contact_person' => 'Mayor Rosario Diaz', 'contact_number' => '+63 (905) 345-6789', 'email' => 'municipal@jiabong.gov.ph', 'address' => 'Jiabong, Samar', 'status' => 'active', 'notes' => 'Small-scale industries and farming'],
            ['name' => 'Basey', 'municipality' => 'Basey', 'province' => 'Samar', 'description' => 'Coastal municipality with boat-building heritage and fishing.', 'contact_person' => 'Mayor Nestor Corpuz', 'contact_number' => '+63 (905) 456-7890', 'email' => 'municipal@basey.gov.ph', 'address' => 'Basey, Samar', 'status' => 'active', 'notes' => 'Boat-building and fishing heritage'],
            ['name' => 'Santo Niño', 'municipality' => 'Santo Niño', 'province' => 'Samar', 'description' => 'Municipal area with agricultural and aquaculture development programs.', 'contact_person' => 'Mayor Josefina Ramos', 'contact_number' => '+63 (905) 567-8901', 'email' => 'municipal@santonino-samar.gov.ph', 'address' => 'Santo Niño, Samar', 'status' => 'active', 'notes' => 'Aquaculture development focus'],
            ['name' => 'Pinabacdao', 'municipality' => 'Pinabacdao', 'province' => 'Samar', 'description' => 'Municipality with fishing industry and marine resource management.', 'contact_person' => 'Mayor Benjamin Reyes', 'contact_number' => '+63 (905) 678-9012', 'email' => 'municipal@pinabacdao.gov.ph', 'address' => 'Pinabacdao, Samar', 'status' => 'active', 'notes' => 'Marine resource management'],
            ['name' => 'Pandi', 'municipality' => 'Pandi', 'province' => 'Samar', 'description' => 'Agricultural municipality with vegetable and rice farming.', 'contact_person' => 'Mayor Florencia Castillo', 'contact_number' => '+63 (905) 789-0123', 'email' => 'municipal@pandi.gov.ph', 'address' => 'Pandi, Samar', 'status' => 'active', 'notes' => 'Vegetable and rice farming hub'],
            ['name' => 'Almagro', 'municipality' => 'Almagro', 'province' => 'Samar', 'description' => 'Rural municipality with farming, fishing, and coconut fiber processing.', 'contact_person' => 'Mayor Leonardo Santos', 'contact_number' => '+63 (905) 890-1234', 'email' => 'municipal@almagro.gov.ph', 'address' => 'Almagro, Samar', 'status' => 'active', 'notes' => 'Coconut fiber processing industry'],
            ['name' => 'Gandara', 'municipality' => 'Gandara', 'province' => 'Samar', 'description' => 'Municipality with agricultural production and community livelihood programs.', 'contact_person' => 'Mayor Victoria Espinosa', 'contact_number' => '+63 (905) 901-2345', 'email' => 'municipal@gandara.gov.ph', 'address' => 'Gandara, Samar', 'status' => 'active', 'notes' => 'Community livelihood programs'],
            ['name' => 'Matuguinao', 'municipality' => 'Matuguinao', 'province' => 'Samar', 'description' => 'Rural community with agricultural focus and development initiatives.', 'contact_person' => 'Mayor Alfonso Tolentino', 'contact_number' => '+63 (905) 012-3456', 'email' => 'municipal@matuguinao.gov.ph', 'address' => 'Matuguinao, Samar', 'status' => 'active', 'notes' => 'Agricultural development initiatives'],
        ];

        foreach ($communities as $community) {
            Community::firstOrCreate(
                ['name' => $community['name'], 'municipality' => $community['municipality']],
                $community
            );
        }
    }
}
